### ISSUE TITLE
2019 겨울방학 MT 기획

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#1]
- [x] 날짜 정하기
- [x] 장소 정하기 및 예약
- [x] MT 계획

**Comment by kingsj0405** [comment]
카카오톡 투표 올림

**Comment by kingsj0405** [comment]
[기획 문서](https://docs.google.com/document/d/1wbs6bwYEBNsndj5bufdKNsl9T5QNtJVLeyy326dAHV4/edit?usp=sharing)

**Comment by 221blee** [comment]
MT 활동 아이디어 : 생각나는 데로 추가해주세요
- 보드게임, 카드 게임, 마피아
- 모두가 즐길 수 있는 활동 : 팀별 대결? - 지난번에 컵으로 한 게임
- 약간 노래방 같이? (MC 필요?)

**Comment by kingsj0405** [comment]
- 레크레이션? (당신은 당신의 이웃을 사랑하십니까, 몸으로 말해요)
- 보드게임 같은 경우에 MT랑 별개로 사서 동방에 구비해두는 것도 괜찮을 것 같습니다(투표 같은 거 받아서?)
- 노래방은... 이번에 가는 곳이 호텔이라서 쫓겨날수도 있으니 중간에 코인노래방 갔다오기...?

**Comment by kingsj0405** [comment]
2019년1월26일로 정해짐

![image](https://user-images.githubusercontent.com/13496612/50575642-31a5ea00-0e45-11e9-9a50-2933488c6547.png)

**Comment by kingsj0405** [comment]
투표 안내문

```
안녕! 양세종이에요 :3
즐겁고 씡나는 겨울방학 MT가 찾아왔어요!
1월 느즈막한 신년회 해요!

날짜: 2019.01.26
장소: 서대문역 바비엥 2 주니어 스위트룸(http://www.atriumvabien2.com/sub3/sub3_05.asp)
예상 엠티비: 2만원

무엇이 있을 것인가?
- 고기
- 카나페
- 마시멜로
- 보드카에 과일 음료
- 소주, 맥주
- 그 외에 각자 마시고 싶은 사람들이 가져온 술
- 보드게임(할리갈리 시리즈, 뱅, 트럼프 카드)
- 레크레이션(마피아게임, 몸으로 말해요, 비어퐁)
무엇이 없을 것인가?
- 노래방이 가고 싶은 분들은 알아서 중간에 나갔다 오시기...
```

**Comment by kingsj0405** [comment]
![image](https://user-images.githubusercontent.com/13496612/51399715-f700b900-1b89-11e9-887f-f08f2600e377.png)

**Comment by devjwsong** [comment]
MT 완료
모든 MT 비용 및 지원금 정산 완료
