### ISSUE TITLE
20191 동방 출입 권한 관리

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#10]
- 신입 받고 나서 한 번?
- 그 전에도 일단 한번 더?

**Comment by devjwsong** [comment]
3월에 신입 받고 나서 한번에 처리하는 걸로

**Comment by 221blee** [comment]
동방 출입 - 다른 과에서도 많이 모집한다면 출입카드 시스템 재검토 필요
비공대 학생은 카드 등록이 안되어 출입이 어려운 걸로 알고 있음

**Comment by kingsj0405** [comment]
카드키락은 항상 열고 비밀번호 도어락 도입에 대해 고민해봅시다아

**Comment by kingsj0405** [comment]
[설문지](https://goo.gl/forms/K9SOaLmC2j8nv0Ct2)로 조사 받는 중

**Comment by kingsj0405** [comment]
비밀번호 있는 도어락 도입
