### ISSUE TITLE
풀씨에서 진행한 프로젝트 찾아보기

### ISSUE THREAD

**Issue by devjwsong** [PoolC/admin#12]
프로젝트 이름, 장르, 썸네일, 내용 등

**Comment by devjwsong** [comment]
프로젝트 내역 취합 공지함

**Comment by 221blee** [comment]
진행한 프로젝트 (추가 부탁)
세미나
- UNITY, C++, C#, 딥러닝 등
스터디
= 게임기획, 머신러닝 등

- 엠티
열심히 재밌게 감.

- 개총, 종총
열심히 함

- 새로운 동방으로 이전

- 게임개발
넥슨 (언리얼로 도전 등)
라인

NDC CONFERENCE (앞으론 이런 데 가면 사진 열심히 찍어야겠어요)

**Comment by kingsj0405** [comment]
근데 저건 플젝 말고 뭔가 따로 활동? Activity 같은 거에 넣어도 괜찮을 거 같은데

**Comment by kingsj0405** [comment]
대충 완료 됨
