### ISSUE TITLE
동방 물품 구매

### ISSUE THREAD

**Issue by devjwsong** [PoolC/admin#15]
책상 1(구석에 놓을 수 있게 사이즈 재고)
마우스 2, 키보드 2

**Comment by devjwsong** [comment]
마우스 2, 키보드 2,
문구류, 휴지, 탈취제, 구입 완료

**Comment by devjwsong** [comment]
책상 -> 사이즈 측정
공기청정기 ->  가격 논의 필요

**Comment by kingsj0405** [comment]
책상 오는 중 완료!
