### ISSUE TITLE
2019 구정 맞이 대청소

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#17]
happy new luna year!

**Comment by zych1751** [comment]
했어요?

**Comment by kingsj0405** [comment]
임원진 방에서 청소 날짜 투표 진행중입니다.

**Comment by kingsj0405** [comment]
'신입 들어오기 전에 동아리원도 다 함께 모여서 청소해요'라는 결론이 [20190218 미팅](https://github.com/PoolC/admin/wiki/20190218---1%ED%95%99%EA%B8%B0-%EC%A4%80%EB%B9%84-%ED%9A%8C%EC%9D%98)에서 나왔습니당

**Comment by kingsj0405** [comment]
20180304 월요일 동아리 대청소 수요조사 진행 중

**Comment by kingsj0405** [comment]
다음과 같이 변경
![image](https://user-images.githubusercontent.com/13496612/53730219-a2f03080-3eba-11e9-9920-5c8b4b764111.png)
