### ISSUE TITLE
필수 세미나 메뉴얼 만들기

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#18]
다음과 같은 세미나들은 동아리의 유지를 위해서 매학기 세미나가 열리는 것이 권장됩니다.
단순히 세미나를 여는 것뿐 아니라 다음 학기를 위한 후계자(?) 양성 및 세미나 메뉴얼의 작성이 필요하다고 생각됩니다.

- Git/Github 세미나: @HelloDHLyn (3월 21일 목요일 6시-8시)
- 게임 제작 세미나: @bomul0327 
  -  1회성으로 어려운 수업이라서 지원자들 수준에 따라서 어떤 수업을 할지 고민을 해봐야함
  - 지원자 서류를 함께 검토
  - 혹은 4주동안 목요일 8시-10시...(논의 필요)
- 게임 기획 세미나: 이상원
- 딥러닝 세미나: 찾아야함
- 기본 언어 세미나(Python, Java, C/C++ 등): 찾아야함

**Comment by kingsj0405** [comment]
기존 세미나보다 더 많은 특전을 줄 계획입니다

**Comment by 221blee** [comment]
기초 파이썬 조금 정리해봤어요. .. 아직 만드는 중이지만 일단 올려봅니다

[Python Basics.pptx](https://github.com/PoolC/admin/files/2930815/Python.Basics.pptx)

**Comment by devjwsong** [comment]
<세미나 및 스터디 계획(예정)>

-  기초 세미나
    - Git/Github
    - Python
    - C/C++
    - 웹(dJango)

- 개별 세미나
    - 게임 기획
    - Unity 기초
    - Unity 중급
    - 딥러닝 기초

- 스터디
    - 머신러닝/데이터과학

**Comment by kingsj0405** [comment]
세미나 메뉴얼 작성은 어렵고 기존과 같이 풀씨 홈페이지에 ppt 내용 등을 공유하는 것으로 합니다
