### ISSUE TITLE
전체 명부 관리하기

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#2]
전화번호, 이메일 등 공개하고 싶은 사람에게만 공개 가능하도록 만들어야한다.

구글드라이브나 홈페이지?

**Comment by hellodhlyn** [comment]
이미 홈페이지 어드민 페이지에 있음 (단 현재는 관리자만 접근 가능)

**Comment by kingsj0405** [comment]
아 그러네 그럼 그건 홈페이지 리뉴얼 쪽에서 다루어야할 이슈로군 클로즈!
