### ISSUE TITLE
개강 총회 및 신입생 OT 준비

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#20]
3.14에 진행되는 개강 총회 및 신입생 OT를 준비한다

1. 강의실 대관 진행 중
2. 신입생들을 세미나/스터디/프로젝트 중 하나에 집어넣고 거기에 기존 부원을 섞는다

**Comment by 221blee** [comment]
- 개강종회 참석할 기존 멤버 파악
- 아이스브레이킹 ?ㅎ

**Comment by devjwsong** [comment]
<개강총회 개요>
- 장소: 미정
- 일시: 2019/03/14(목) 오후 6시
- 내용
    - 동아리 소개
    - 임원진 소개
    - 세미나/스터디(담당자도)
    - 라인/넥슨 게임
    - 회원자격 유지 조건
    - 회칙(동방 사용이나 징계 등 베이직한 내용만)
    - 한 학기 동안의 계획 및 절차(세미나/스터디 신청, 행사, 기타 일정)
    - 풀씨 홈페이지 간단하게 설명/플러스 친구 가입
    - 질의응답
    - 뒷풀이 장소 공지 및 마무리

**Comment by kingsj0405** [comment]
공A542 대관

**Comment by kingsj0405** [comment]
![photo6088919967140522163](https://user-images.githubusercontent.com/13496612/54510265-f1f49600-498f-11e9-9215-b6b7e1e66587.jpg)
![photo6086880489035114675](https://user-images.githubusercontent.com/13496612/54510266-f1f49600-498f-11e9-9423-246b5c50d922.jpg)
![photo6088919967140522162](https://user-images.githubusercontent.com/13496612/54510267-f28d2c80-498f-11e9-8687-692a6293a41b.jpg)
![photo6086880489035114674](https://user-images.githubusercontent.com/13496612/54510268-f28d2c80-498f-11e9-98a8-3f621eb11421.jpg)
