### ISSUE TITLE
우리 한 몸 뉘일 곳은 어디에...

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#22]
- [20190312 동방관련 긴급회의 - Github WIKI](https://github.com/PoolC/admin/wiki/20190312-동방-관련-긴급회의)
- [2019-1 동방 관련 자료 - Google Drive](https://drive.google.com/drive/folders/1IrlwXYpYB5ddeBDe_GctDz1UJCo0LcA0?usp=sharing)

**Comment by kingsj0405** [comment]
20190313 공동연장을 통해 공대 회장에게 우리의 입장을 전달해 줄 것을 부탁하고 대기 중

**Comment by devjwsong** [comment]
공동연장에게 공운위 결정 사항에 대해서 전달받음. 전달 사항은 다음과 같음.
- 풀씨가 학기 중에 동방을 옮기게 될 확률은 낮다. 이것저것 절차를 처리해야하는데 학기 중에 이루어지기엔 무리가 있다. 다만 공학 11반의 과방이 2학기 전에는 마련이 되어야하므로 방학 중에 이사를 하게 될 가능성이 가장 크다.
- 이사에 발생하게 될 비용 문제는 풀씨의 불이익을 충분히 인지하고 있으므로 배려해주는 방향으로 갈 것이다.(다만 어떤 배려가 될 지는 아직 모름. 저쪽에서도 구체적으로 무슨 방안이 있어서 한 말이 아니라 일단 요구를 했으니 좋게 얘기하고 넘어간 듯한...)
- 추가적으로 공동연 회의에서 공대 정의 부적절한 사견 표현 및 권한을 넘어선 듯한 발언에 대해서는 공대 정 측에서 그런 것이 아니었다고 일체 부정 중. 각 사유에 대한 그 정도 의견 표출은 충분히 가능하다고 생각하며 최종적으로 그것이 적절한지 부적절한지는 동아리 대표들이 결정한 것이지 본인이 한것이 아니라고 함. 또한 이전 공동연 회의에서 풀씨가 우선순위를 받은 것에 대해 잘못되었다고 말한 것이 아니라 자치 공간이 줄었는데 늘은 것으로 잘못 인지하고 있었음을 지적한 것이라고 함. 결론적으로 자긴 풀씨보고 나가라고 한 적 없고 결정은 동아리 대표들이 한 것이다라는 거임.

**Comment by kingsj0405** [comment]
그럼 우선 관련사항은 방학까지는 문제가 없을테니 이슈 close합니다
나중에 관련 업데이트가 있을 경우 리오픈
