### ISSUE TITLE
2019.03.22 지도교수님과의 면담 내용

### ISSUE THREAD

**Issue by devjwsong** [PoolC/admin#23]
1. 동아리 인원 유지에 힘쓸 것. 이번에 신입 많이 들어왔으니 주기적인 활동을 통해 내실을 다지는 데에 최선을 다할 것.
2. 동아리방 문제는 동아리 회장단끼리의 투표로 결정된 사항이므로 학교나 교수님 입장에서 해줄 수 있는 부분이 없음.
3. 파이썬 수업 조교 할 사람 있는지? 페이는 시간당 15000 ~ 20000정도 될 것 같고 한두시간 정도 과제나 실습할 때 모르는 사항 Q&A 받아주는 정도.
4. 방학동안 프로그래밍 경진 대회를 할 예정인데(아직 구체적인 내용은 말씀 안 하심) 그걸 도와줄 인력 확보가 가능한지?
(3, 4는 꼭 하라는 건 아니고 그냥 물어본 정도. 우선은 1을 가장 우선시하라고 말씀하심)

**Comment by kingsj0405** [comment]
이거 딱히 뭐 테스크 없으면 위키로 옮기고 닫아도 될듯?

**Comment by kingsj0405** [comment]
[위키](https://github.com/PoolC/admin/wiki/20190322-%EA%B5%90%EC%88%98%EB%8B%98%EA%B3%BC%EC%9D%98-%EB%A9%B4%EB%8B%B4)에 작성
