### ISSUE TITLE
MT? MT!

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#24]
- [ ] 수요조사
- [ ] 장소 탐색
- [ ] 프로그램 기획
- [ ] 실제 예약 및 확정

**Comment by 221blee** [comment]
* 날짜 확정 후 참가 가능 여부 확인 - option 1 / 날짜 투표 - option 2
  option 1 : 인원이 많아 투표를 올려도 조율 어려울 수 밖에 없으며, 그럴 거면 이왕 지정하는 것이 좋을 것. ADV: 조금 더 정리된 진행

  option 2  : 일정 조율의 노력 보임

작성자 : 날짜 확정을 우선 하는 것이 좋겠음 

* 장소 : 논의 필요할 듯 
* 프로그램 기획 : 보드게임, 술게임 등ㅎㅎㅎ 그리고 어디가느냐에 따라 분위기에 맞게 잘 기획

**Comment by kingsj0405** [comment]
중간발표를 엠티에서?

**Comment by kingsj0405** [comment]
수요조사 받았고 장소는 우이동 월벽타운으로 예약 완료

**Comment by devjwsong** [comment]
MT를 무사히 마쳤음.
