### ISSUE TITLE
20191 신입 홍보 및 모집

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#4]
20191 정원은 임원진 수 * (3~5) 정도로 생각

```
홍보를 우선 많이 한다
정기모임(세미나) 출석 가능한가
세미나, 게임제작, 스터디 뭐든 한 그룹에는 들어가서 활동하셔야 한다는 것 같이 홍보한다
기획/제작/디자인 밸런스를 맞게 뽑아야합니다
서류, 면접
회비, 뒤풀이비
각 기수 = 회장단 * (3 ~ 5)
```

**Comment by kingsj0405** [comment]
[20182 종강총회록](https://gist.github.com/kingsj0405/27243865740967be5537dfbeeac9590a)을 염두에 둘 것

**Comment by 221blee** [comment]
서류 및 면접 절차를 다음 학기부터 시행할 것인지 논의가 필요하다고 생각이 들어요. 홍보를 열심히 하여 학교 내 풀씨 인지도를 우선 높여야 우리가 뽑고 말고 할 인원이 있지 않을까...

**Comment by kingsj0405** [comment]
```
#20181231 풀씨 20191 임원진 단톡방
[양세종] [오전 10:21] 과연 면접을 볼 것인가?인데 종총에서 말했던대로 '그래도 면접을 보고 들어왔다'는 효과를 주기 위해서 해야하는가?도 요점이고
[양세종] [오전 10:23] 흠 지원자가 몇 명이나 될지를 모르겠네... @이정현 20181 20171 지원자 몇명이야
[이정현] [오전 10:25] 그건
[이정현] [오전 10:25] 정이히ㅡㄴ테
[이정현] [오전 10:25] 정이랑 재혁이
[이정현] [오전 10:25] 난 모름ㅋㅋ
[이미선] [오전 10:28] 2018년 1학기는 처음에 톡방에 한 30명 있었던 거 같아요
[Jason] [오전 10:28] 맞아여
[Jason] [오전 10:28] 면접보져 뭐
[Jason] [오전 10:28] 빤스런할것 같은 사람들은 좀 거르고...
[양세종] [오전 10:29] 사실 빤스런도 빤스런인데 12명이하라도 진짜 이상한 사람은 걸러야하는 거 같은 ㄸㄹ
[Jason] [오전 10:29] 네 그냥 뭐든간에 면접 보져
[양세종] [오전 10:29] 아마 톡방은 기존부원도 있었을테니...
[Jason] [오전 10:29] 임원진은 교대로 들어가고
[이미선] [오전 10:29] 음 처음부터 거르고 시작하자... 넹넹
[이미선] [오전 10:29] 그렇게 합시당
[Jason] [오전 10:29] 기존에 지원했다 빤쓰런한 사람들 리스트 가지고 비교하고
[Jason] [오전 10:30] 1. 자소서 혹은 동아리 지원 신청서 작성
(리스트 대조 후 면접행)
2. 면접
(이상하거나 뭔가 조짐이 심상치 않다 싶으면 빠꾸)
[양세종] [오전 10:31] 아앜 근데 저 말 듣고 보니까
[양세종] [오전 10:31] 역시 중동도 아니고 단과대 동아리에서
[양세종] [오전 10:31] 면접은 투머치인가
[양세종] [오전 10:31] 하와와
[양세종] [오전 10:31] 어려운거시어요
[이미선] [오전 10:31] 홍보가부족한 동아리에서 면접을 하기엔
[이미선] [오전 10:31] 좀 그럴 수 있겠단 생각에서
[이미선] [오전 10:31] 질문 던지긴 했었어요
[양세종] [오전 10:33] 임원진 대부분 MT오는 거 같으니
[양세종] [오전 10:33] 그 때 좀더 얘기해봅시다아
.
.
.
[Jason] [오전 11:03] 면접 근데 단과대동아리도 보지 않나요??? 아닌감...
.
.
.
[송재우] [오전 11:03] 사실 면접은 자유긴 해요
.
.
.
[양세종] [오전 11:05] 뭐 보는 곳은 보는데
[송재우] [오전 11:05] 당장 과동아리에서 보는 곳은 보는데
[양세종] [오전 11:05] 우리가 뭐라고 면접을 보나... 뭐 그런 느낌?
[송재우] [오전 11:05] 그만큼 사람이 많이 몰리고 인원 제한이 있을 때 많이 보죠
[송재우] [오전 11:05] 풀씨는 그동안 그런게 없었으니
[Jason] [오후 12:02] 면접을 그냥 면접이 아니라 임원진들이랑 친해질 수 있는 계기라고 생각하면 되지 않을따요
[Jason] [오후 12:02] 미꾸라지 한마리가 물 흐릴수도 있으니
[Jason] [오후 12:02] 비품이 가면갈수록 마련되고 있으니 분실 염려 등도 있을 수 있으니
[양세종] [오후 12:06] + 그럼 면접을 임원진에 국한시키는 게 아니라 기존 부원 중에서도 관심있는 사람이 같이 하는 것도 괜찮을듯여?
[양세종] [오후 12:07] 어차피 공통 질문 리스트 정도 만들어두고 하면 될테니
```

**Comment by kingsj0405** [comment]
신입이 들어오기전에 세미나 1차 신청을 받아서 어떤 수업이 열릴지 확정한 다음 신입 홍보에 같이 쓰는 것도 괜찮을 것 같아요.
OB 분들의 특강도 환영...!

**Comment by kingsj0405** [comment]
https://poolc.github.io/20191_welcome/

동아리 홍보 홈페이지를 만들었는데 다음과 같은 내용이 추가되어야합니다

- 정기모임(요일 정해야함)
- 스터디 및 작은 세미나에 대한 내용
- 서류와 면접 내용
- 회비(금액 정해야함)

**Comment by kingsj0405** [comment]
[설문지](https://docs.google.com/forms/d/1k__Hfu6Q2cYMAPY_sUbUSPUDajnacsFnzGU0aFBaP78/edit?usp=sharing) 제작

**Comment by kingsj0405** [comment]
포스터와 함께 SNS에 뿌려달라고 해야함

```
안녕하세요.
공과대학 프로그래밍 동아리 풀씨입니다!
저희는 웹, 안드로이드, 머신러닝/딥러닝, 게임 제작, 알고리즘 등 여러 프로그래밍 분야를 함께 공부하고 응용하는 데 그 목적이 있습니다!
비전공자도 전공자도 와서 배울 수 있도록 많은 것을 준비해두었습니다.

SNS용 포스터 상태를 보면 알겠지만 기획자와 디자이너도 많이 와주세요 흡...
개발자와 대화 가능한 기획자와 디자이너는 중요하답니다.

관심 있으신 분은 3.6(수)까지 아래 링크의 설문지를 작성해주세요!
동아리 활동에 대한 자세한 내용은 설문지에 있습니다.
또 궁금하신 점은 카카오톡 플러스친구에서 '풀씨'를 검색하시거나 홈페이지에 방문해서 회장에게 연락을 주세요.
감사합니다!

https://bit.ly/2ScooxH
```

**Comment by kingsj0405** [comment]
![sns](https://user-images.githubusercontent.com/13496612/53155706-f59b3400-3600-11e9-8a19-d0a40b71f4b3.jpg)

이 정도면 훌륭하지 않나

**Comment by kingsj0405** [comment]
![kakaotalk_20190222_160432359](https://user-images.githubusercontent.com/13496612/53570501-04a65700-3baa-11e9-99e8-5d2d1d262c43.png)

**Comment by kingsj0405** [comment]
생각보다 지원자 수가 많아서 25명 max로 면접을 봐야할 듯...

**Comment by kingsj0405** [comment]
다음 시간에 회장, 부회장 필수 참여 다른 임원진 선택 참여로 면접을 진행합니다. 

3.7(목) 오후 6시 ~ 오후9시
3.8(금) 오전 11시 ~ 오후1시

**Comment by kingsj0405** [comment]
면접 질문 리스트

- 관심분야
- OT 및 정기모임 참석 가능한지(목요일 6시)
- 활동예정기간은?
- 동아리에 투자할 수 있는 시간은?
- 궁극적으로 얻어가고 싶은 것이 무엇인가요?(무언가 게임을 만들고 싶다, 블로그를 만들고 싶다, 캐글에서 상타고 싶다)
- 마지막으로 궁금한 점이나 하고 싶은 말이 있으신가요?
- 관심 있는 세미나/스터디
  - 게임 기획 세미나
  - Unity, Unreal(게임제작, !!!!!중요!!!!!), 웹게임...?
  - 웹(FrontEnd, BackEnd, Web Crawling + Semantic Web)
  - 앱(Android)
  - 머신러닝/딥러닝
  - 기초언어 세미나(C/C++, Java, Python, Ruby)
  - 정보보안
  - Problem Solving(Algorithm)
  - 운영체제(PintOS)

**Comment by kingsj0405** [comment]
기본적으로 면접에서 떨어뜨리지는 않는다고 생각하고 다 뽑는다
개강 총회 및 신입생 OT에서 팀을 구성하는데 거기서 다 못 들어가면 사실상 포기하는 것으로
[면접 시간 타임라인](https://docs.google.com/spreadsheets/d/1mJ0JCQnWQy4fT5fp2yR90GPpOETj-O4jhAuE79Y57iA/edit?usp=sharing)

**Comment by kingsj0405** [comment]
> 면접 질문 리스트
> 
> * 관심분야
> * OT 및 정기모임 참석 가능한지(목요일 6시)
> * 활동예정기간은?
> * 동아리에 투자할 수 있는 시간은?
> * 궁극적으로 얻어가고 싶은 것이 무엇인가요?(무언가 게임을 만들고 싶다, 블로그를 만들고 싶다, 캐글에서 상타고 싶다)
> * 마지막으로 궁금한 점이나 하고 싶은 말이 있으신가요?
> * 관심 있는 세미나/스터디
>   
>   * 게임 기획 세미나
>   * Unity, Unreal(게임제작, !!!!!중요!!!!!), 웹게임...?
>   * 웹(FrontEnd, BackEnd, Web Crawling + Semantic Web)
>   * 앱(Android)
>   * 머신러닝/딥러닝
>   * 기초언어 세미나(C/C++, Java, Python, Ruby)
>   * 정보보안
>   * Problem Solving(Algorithm)
>   * 운영체제(PintOS)

**Comment by kingsj0405** [comment]
[지원서](https://docs.google.com/spreadsheets/d/1lCeSmwuEcRXN3ZDlw66_8jplzQQuc1_zh6Dj4cxP0rY/edit?usp=drivesdk)에 면접 코멘트 정리한후 각 답변별 점수 계산

자소서 읽고 특정이유 있을경우 색칠해놓고 가산점 부여

주요 면접 완료 우선 정리했을 때 60명 합격, 5명 토요일 면접 남음

**Comment by kingsj0405** [comment]
- 토요일에 면접
- 일요일에 합격자 신입 단톡방 파고 공지로 기획 세미나/유니티 중급 세미나 수요조사 받음
  - [ ] 상원이 형 실라버스
  - [ ] 정이 실라버스
- 일요일에 불합격자에게 문자를 보냄

**Comment by kingsj0405** [comment]
[풀씨 지원서](http://bit.ly/풀씨20191지원서취합)에서 면접관 코멘트를 조정하고 점수를 조정한 결과 8점까지 붙이면 45명 합격

**Comment by devJWSong** [comment]
신입생 합격 명단 첨부
[2019-1 신입생 합격 명단.xlsx](https://github.com/PoolC/admin/files/2948181/2019-1.xlsx)

**Comment by kingsj0405** [comment]
공지 하고 방 파야 끝나는 거 아닐까

**Comment by kingsj0405** [comment]
[20191 합격자 명단](https://drive.google.com/file/d/1TxfhACPkAkVfGepnZd9la8NC_ghPcEZE/view?usp=sharing)

**Comment by 221blee** [comment]
파일로 업로드 부탁

**Comment by kingsj0405** [comment]
@221blee 개인정보때문에 일부러 임원진만 볼 수 있게 링크로 올린건데 혹시 안 보이시나여?

**Comment by kingsj0405** [comment]
수정!

**Comment by 221blee** [comment]
왜 안 열리지ㅠㅠ 흑 제가 구글 로그인을 해야 되는 건가요

**Comment by kingsj0405** [comment]
얍 구글 로그인 해야합니다

**Comment by kingsj0405** [comment]
근데 이건 이제 완료된 거 아닌가

**Comment by 221blee** [comment]
ㅇㅇ 명단 출력하려구 들어왔어
