### ISSUE TITLE
일정 관리를 어떻게 할지 고민...

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#6]
구글 드라이브에 문서로?
구글 캘린더?

**Comment by kingsj0405** [comment]
[구글드라이브 일정](https://docs.google.com/document/d/1bwiL6clm2fOi8dr22qkfl6XmiwC8Em-88XLUbAQ2QWw/edit?usp=sharing)

**Comment by kingsj0405** [comment]
투머치 그냥 공지사항에 글로 작성해 놓는다

**Comment by hellodhlyn** [comment]
FYI) 기존에는 구글 캘린더로 했었고 슬랙에 연동 알림도 쏴주고 있었음
