### ISSUE TITLE
총무 인수인계

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#8]
- 통장파기
- 돈 받기
- 회계장부와 체크하기

**Comment by devjwsong** [comment]
통장 및 계좌 개설 완료

**Comment by kingsj0405** [comment]
이거 하면서 명부랑 회계장부 merged version 만드는 것도 하자

**Comment by devjwsong** [comment]
회계장부는 일단 아예 새로 만들건데 전꺼랑 굳이 merge할 필요 있나?
이름 통일해서 백업만 해두면 되지 않을까

**Comment by kingsj0405** [comment]
그렇게 해도 되긴한데 나같은 경우엔 엠티비 얼마 나갔는지 검색하는데 정리되있으면 편할거 같더라고

날짜 집행자 집행임원단 항목 가격

위 내용 정도 있으면 아카이브 되있어서 뒤의 임원진들이 참고하기 편할거 같아서? 여기 이슈 쓰는 것도 뒤의 임원진들 검색하기 편하라고 하는 것처럼 ㅇㅇ

근데 작은 일은 아니라서 각좀 재보고 아니다 싶으면 형말대로 ㄱㄱ

**Comment by devjwsong** [comment]
회계 내역 통합 완료
이제부턴 회계 내역 파일에 이어서 작성

**Comment by devjwsong** [comment]
돈은 100만원씩 끊어받아야 하는데 일단 100만원 오늘 받음

**Comment by devjwsong** [comment]
돈 전액 수령 완료

**Comment by kingsj0405** [comment]
그럼 이 이슈는 완료된 건가요?

**Comment by devjwsong** [comment]
ㅇㅋ완료

**Comment by kingsj0405** [comment]
그럼 Close
