### ISSUE TITLE
MT + 동방에 보관 해둘 보드게임 구매

### ISSUE THREAD

**Issue by kingsj0405** [PoolC/admin#9]
- 여럿이 할 수 있는가
- 보관 및 관리가 용이한가(ex. 카드밴)
- 투표 받아서 처리

**Comment by 221blee** [comment]
뱅뱅뱅 재밌자나요 한 8명정도 할 수 잇음
당연히 카드는 있어야 하구
모노폴리? 
젱가?
여럿이 할 수... 윷놀이도 은근 재밌음ㅋㅋㅋㅋ

**Comment by kingsj0405** [comment]
ㅇㅇ 그럼 여기서 대충 미리 투표에 올릴 리스트 뽑고 항목 추가까지 받아봅시다
MT 수요조사 및 날짜선정 끝나고 MT 참여조사랑 같이 투표로 올림
이 댓글을 바로 수정해주시면 됩니당(수정자 및 history 남음)

- 뱅
- 모노폴리
- 젠가
- 윷놀이(...)
- 바퀴벌레 카드게임
- 할리갈리 시리즈
- 티츄
- 마이티(a.k.a. 서양화)
- 민화투(a.k.a. 동양화)

**Comment by kingsj0405** [comment]
![image](https://user-images.githubusercontent.com/13496612/50869078-ed42bd00-13f5-11e9-85ab-00c2c8a2dae4.png)

**Comment by doodoori2** [comment]
@kingsj0405 slack 개인 메시지좀 봐주세요!

**Comment by kingsj0405** [comment]
슬랙 노티가 안 오고 있었네요 확인 했습니다!

**Comment by doodoori2** [comment]
MT가 언젠진 모르겠지만, 개인적인 파티용 추천으로 동방으로 택배 보냈습니다. 
추가로 구매하더라도 아래 목록은 제외하고 구매하심 될 것 같아요 
뱅, 할리갈리, 할리갈리컵스, 티츄, 컬러레또, 5분던전
마헤,한밤의늑대인간,하나비,벼룩서커스,너도나도,카드홀더

**Comment by kingsj0405** [comment]
contribution 감사합니다 :) 👍 💯 🥇 
새해복 많이 받으세요!

**Comment by kingsj0405** [comment]
![image](https://user-images.githubusercontent.com/13496612/51116755-5049af00-184f-11e9-84f2-c9942740811a.png)

도착 및 동방 구비 완료

```
행복한 바오밥(?)
할리갈리 컵스
마헤
5분던전
하나비
컬러레또
벼룩서커스
티츄
뱅
너도?나도!
한밤의늑대인간
할리갈리
```
